# Bosonic SU2 model: Result preprocessing (EvolvedOp)


Notebook created by HLD for the work arXiv: 2503.13368 [quant-ph, hep-th]

In [1]:
import pandas as pd
import numpy as np
import time

import sys
sys.path.append('../../utility')
from L4_evop_data_collate import *

E_02 = 3.14808
E_05 = 3.36254
E_10 = 3.69722
E_20 = 4.26795

In [2]:
def load_and_split(link):
    df = pd.read_csv(link)
    df.drop(['Unnamed: 0'], axis = 1, inplace=True)
    df_c = df[df.columns[:9]]
    df_s = df[df.columns[9:]]
    col_names = ['ev_op_r', 'ev_op_r3', 'ev_op_H', 'ev_op_H_2f',
       'ev_op_H_3f', 'ev_op_Hp', 'ev_op_Hp2', 'ev_op_Hp3',
       'ev_op_Hp4']
    df_c.columns = col_names
    df_s.columns = col_names
    return df_c, df_s

# l = 0.2

In [8]:
df_l02_old = pd.read_csv('results/l02_last_val.csv')
df_02c_170, df_02s_170 = load_and_split('results/l2_l0.2_op_ev_seed_170.csv')
df_02c_225, df_02s_225 = load_and_split('results/l2_l0.2_op_ev_seed_225.csv')

In [5]:
l02_collate = EvOpAnsatz_data_collate(df_02c_170, df_02c_225, df_02s_170, df_02s_225, 170, 225, E_02, 0.2)

file saved as results_tests/l0.2_last_val_170.csv
file saved as results_tests/l0.2_last_val_225.csv
Checking COBYLA column
ev_op_r: seed_170
ev_op_r3: seed_225
ev_op_H: seed_225
ev_op_H_2f: seed_170
ev_op_H_3f: seed_170
ev_op_Hp: seed_225
ev_op_Hp2: seed_225
ev_op_Hp3: seed_170
ev_op_Hp4: seed_170
Checking SPSA column
ev_op_r: seed_225
ev_op_r3: seed_225
ev_op_H: seed_225
ev_op_H_2f: seed_170
ev_op_H_3f: seed_225
ev_op_Hp: seed_170
ev_op_Hp2: seed_225
ev_op_Hp3: seed_170
ev_op_Hp4: seed_225
file saved as results_tests/l0.2_last_val_best.csv

In [6]:
l02_collate.df_last_best

            cobyla_values  spsa_values
name
ev_op_r           3.14980      3.14863
ev_op_r3          3.15078      3.14844
ev_op_H           3.15000      3.14863
ev_op_H_2f        3.15000      3.15488
ev_op_H_3f        3.14883      3.15332
ev_op_Hp          3.15059      3.14980
ev_op_Hp2         3.15156      3.15156
ev_op_Hp3         3.14902      3.15254
ev_op_Hp4         3.14844      3.15273

In [7]:
l02_collate.df_last_best - E_02

            cobyla_values  spsa_values
name
ev_op_r           0.00172      0.00055
ev_op_r3          0.00270      0.00036
ev_op_H           0.00192      0.00055
ev_op_H_2f        0.00192      0.00680
ev_op_H_3f        0.00075      0.00524
ev_op_Hp          0.00251      0.00172
ev_op_Hp2         0.00348      0.00348
ev_op_Hp3         0.00094      0.00446
ev_op_Hp4         0.00036      0.00465

In [12]:
df_l02_old.set_index('name',inplace = True)
df_l02_old - E_02

            cobyla_values  spsa_values
name
ev_op_r           0.00172      0.00172
ev_op_r3          0.00309      0.00309
ev_op_H           0.00309     -0.00140
ev_op_H_2f        0.00192      0.00680
ev_op_H_3f        0.00075      0.04040
ev_op_Hp         -0.00062      0.00172
ev_op_Hp2        -0.00003      0.00563
ev_op_Hp3         0.00094      0.00446
ev_op_Hp4         0.00036      0.00622

In [23]:
l02_collate.df_c_best.to_csv('results/l_02_cc_cobyla.csv')
l02_collate.df_s_best.to_csv('results/l_02_cc_spsa.csv')

## l = 0.5

In [25]:
df_l05_old = pd.read_csv('results/l05_last_val.csv')
df_l05_old.set_index('name', inplace = True)
df_05c_170, df_05s_170 = load_and_split('results/l2_l0.5_op_ev_seed_170.csv')
df_05c_225, df_05s_225 = load_and_split('results/l2_l0.5_op_ev_seed_225.csv')
df_05c_88, df_05s_88 = load_and_split('results/l2_l0.5_op_ev_seed_88.csv')

In [15]:
df_l05_old  - E_05

            cobyla_values  spsa_values
name
ev_op_r           0.01197      0.01197
ev_op_r3          0.01051      0.01100
ev_op_H           0.00660      0.00904
ev_op_H_2f        0.00758      0.12623
ev_op_H_3f        0.00172      0.21998
ev_op_Hp          0.01734      0.01197
ev_op_Hp2         0.01100      0.00562
ev_op_Hp3         0.01490      0.00465
ev_op_Hp4        -0.00170      0.02076

In [16]:
l05_collate = EvOpAnsatz_data_collate(df_05c_170, df_05c_225, df_05s_170, df_05s_225, 170, 225, E_05, 0.5)

file saved as results_tests/l0.5_last_val_170.csv
file saved as results_tests/l0.5_last_val_225.csv
Checking COBYLA column
ev_op_r: seed_170
ev_op_r3: seed_225
ev_op_H: seed_225
ev_op_H_2f: seed_225
ev_op_H_3f: seed_170
ev_op_Hp: seed_225
ev_op_Hp2: seed_225
ev_op_Hp3: seed_225
ev_op_Hp4: seed_225
Checking SPSA column
ev_op_r: seed_225
ev_op_r3: seed_225
ev_op_H: seed_170
ev_op_H_2f: seed_170
ev_op_H_3f: seed_170
ev_op_Hp: seed_225
ev_op_Hp2: seed_170
ev_op_Hp3: seed_170
ev_op_Hp4: seed_225
file saved as results_tests/l0.5_last_val_best.csv

In [18]:
l05_collate.df_last_best - E_05

            cobyla_values  spsa_values
name
ev_op_r           0.01197      0.00904
ev_op_r3          0.00855      0.01051
ev_op_H           0.00318      0.00904
ev_op_H_2f        0.00074      0.12623
ev_op_H_3f        0.00172      0.21998
ev_op_Hp          0.01197      0.01197
ev_op_Hp2         0.00269      0.00562
ev_op_Hp3         0.00514      0.00465
ev_op_Hp4        -0.00121      0.00855

In [20]:
l05_collate.df_last_best

            cobyla_values  spsa_values
name
ev_op_r           3.37451      3.37158
ev_op_r3          3.37109      3.37305
ev_op_H           3.36572      3.37158
ev_op_H_2f        3.36328      3.48877
ev_op_H_3f        3.36426      3.58252
ev_op_Hp          3.37451      3.37451
ev_op_Hp2         3.36523      3.36816
ev_op_Hp3         3.36768      3.36719
ev_op_Hp4         3.36133      3.37109

In [29]:
l05_collate.df_c_best.to_csv('results_tests/l05_cc_cobyla_170_225.csv')
l05_collate.df_s_best.to_csv('results_tests/l05_cc_spsa_170_225.csv')

In [26]:
df_05c_0 = l05_collate.df_c_best
df_05s_0 = l05_collate.df_s_best

In [27]:
l05_collate_v2 = EvOpAnsatz_data_collate(df_05c_0, df_05c_88, df_05s_0, df_05s_88, 0, 88, E_05, 0.5)

file saved as results_tests/l0.5_last_val_0.csv
file saved as results_tests/l0.5_last_val_88.csv
Checking COBYLA column
ev_op_r: seed_0
ev_op_r3: seed_0
ev_op_H: seed_0
ev_op_H_2f: seed_0
ev_op_H_3f: seed_0
ev_op_Hp: seed_0
ev_op_Hp2: seed_0
ev_op_Hp3: seed_0
ev_op_Hp4: seed_88
Checking SPSA column
ev_op_r: seed_0
ev_op_r3: seed_0
ev_op_H: seed_0
ev_op_H_2f: seed_88
ev_op_H_3f: seed_88
ev_op_Hp: seed_0
ev_op_Hp2: seed_0
ev_op_Hp3: seed_0
ev_op_Hp4: seed_0
file saved as results_tests/l0.5_last_val_best.csv

In [28]:
l05_collate_v2.df_last_best

            cobyla_values  spsa_values
name
ev_op_r           3.37451      3.37158
ev_op_r3          3.37109      3.37305
ev_op_H           3.36572      3.37158
ev_op_H_2f        3.36328      3.37695
ev_op_H_3f        3.36426      3.37354
ev_op_Hp          3.37451      3.37451
ev_op_Hp2         3.36523      3.36816
ev_op_Hp3         3.36768      3.36719
ev_op_Hp4         3.37695      3.37109

In [30]:
l05_collate_v2.df_c_best.to_csv('results/l_05_cc_cobyla.csv')
l05_collate_v2.df_s_best.to_csv('results/l_05_cc_spsa.csv')

## l=1.0

In [32]:
df_10c_170, df_10s_170 = load_and_split('results/l2_l1.0_op_ev_seed_170.csv')
df_10c_170.to_csv('results/l_10_cc_cobyla.csv')
df_10s_170.to_csv('results/l_10_cc_spsa.csv')

## l = 2.0

In [33]:
df_20c_170, df_20s_170 = load_and_split('results/l2_l2.0_op_ev_seed_170.csv')
df_20c_170.to_csv('results/l_20_cc_cobyla.csv')
df_20s_170.to_csv('results/l_20_cc_spsa.csv')